#!/usr/bin/env ansible-playbook

- name: Group hosts by distribution 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distro
      group_by: key={{ ansible_distribution }}

- name: do something to Ubuntu hosts
  hosts: Ubuntu
  sudo: True
  tasks:
    - name: install htop
      apt: name=htop

- name: do something to CentOS hosts
  hosts: CentOS
  sudo: True
  tasks:
    - name: install htop
      yum: name=htop
 
- name: show return value of command module
  hosts: all
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: var=login
    - debug: msg="Logged in as user {{ login.stdout }}"

    - name: Show how to set your own fact 
      set_fact: devan={{ login.stdout }}
    - debug: msg="The devan fact is {{ devan }}"

    - name: Dump baked in variables 
      debug: msg="hostvars = {{ hostvars }}"
    - debug: msg="inventory_hostname = {{ inventory_hostname }}"
    - debug: msg="group_names = {{ group_names }}"
    - debug: msg="groups = {{ groups }}"
    - debug: msg="play_hosts = {{ play_hosts }}"
    - debug: msg="ansible_version = {{ ansible_version }}"
    
- name: Configure web server with Nginx
  hosts: webservers
  sudo: True
  vars:
      config_file: /etc/nginx/sites-available/default
      server_name: localhost 
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=files/nginx.conf dest={{ config_file }}

    - name: enable configuration
      file: >
            src=/etc/nginx/sites-available/default
            dest=/etc/nginx/sites-enabled/default
            state=link

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
