#!/usr/bin/env ansible-playbook

- name: Group hosts by distribution 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distro
      group_by: key={{ ansible_distribution }}

- name: do something to Ubuntu hosts
  hosts: Ubuntu
  sudo: True
  tasks:
    - name: install htop
      apt: name=htop

- name: do something to CentOS hosts
  hosts: CentOS
  sudo: True
  tasks:
    - name: install htop
      yum: name=htop
 
- name: Configure web server with Nginx
  hosts: webservers
  sudo: True
  vars:
      config_file: /etc/nginx/sites-available/default
      server_name: localhost 
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=files/nginx.conf dest={{ config_file }}

    - name: enable configuration
      file: >
            src=/etc/nginx/sites-available/default
            dest=/etc/nginx/sites-enabled/default
            state=link

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
