# Override the default values of the info endpoint
info:
    app:
        name: ${name}
        description: ${description}
        version: ${version}
        realm: development

# enable shutdown of application via a POST
endpoints:
    shutdown:
        enabled: true
    health:
        sensitive: false    # display full details for non-authenticated requests

# show the banner file during startup
spring:
    main:
        show_banner: true
    # Redis configuration (see RedisProperties for details)
    redis:
        database: 0 # redis relies on 0-based index database names
        host: redis
        port: 6379

    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
    datasource:
        url: jdbc:mysql://mysql/jpaexperiment
        username: root
        password: root

    jpa:
        databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
        generateDdl: true
        showSql: true

        hibernate:
            batch_size: 100
            cache:
                use_second_level_cache: true
            connection:
                charSet: UTF-8
                characterEncoding: UTF-8
                isolation: 2
                useUnicode: true
            ddl-auto: create-drop
            format_sql: true
            generate_statistics: false
            id:
#                new_generator_mappings: false
#            naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
            order_inserts: true
            order_updates: true
            show_sql: true
            use_sql_comments: true

# specify the port the service should bind to when using the embedded container, a value of 0 will bind to a randomly selected available port
server:
    port: 0

# be ready for HTTP proxying
    tomcat:
        remote_ip_header: x-forwarded-for
        protocol_header: x-forwarded-proto

security:
    basic:
        enabled: false

# the context to use for the operation actuators, eg /operations/info
management:
    context-path: /operations
    security:
    enabled: false

# operations shell
shell:
    auth:
        simple:
            user:
                name: operations
                password: operations

# which logback configuration file to use
logging:
    config: classpath:logback.xml

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true

example:
    maxPayloadSize: 10
    requireCorrelationId: true

#---------e Profile specific overrides ----------#

# integration testing
---
spring:
    profiles: integration

info:
    app:
        realm: integration-test

# live
---
spring:
    profiles: live

info:
    app:
        realm: production
