---
spring:
    main:
        banner-mode: console
    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
        serialization-inclusion: non_empty

management:
    contextPath: /operations
    security:
        enabled: false
        role: admin
        sessions: stateless

# configure operations endpoints
endpoints:
    health:
        time-to-live: 1000
        sensitive: false

server:
    contextPath: /
    port: 8080
    useForwardHeaders: true
    tomcat:
        portHeader: X-Forwarded-Port
        protocolHeader: X-Forwarded-Protocol-Header
        remoteIpHeader: X-Forwarded-Remote-IP-Header

# which logback configuration file to use
logging:
  config: classpath:logback.xml

# Override the default values of the info endpoint
info:
  app:
    name: ${name}
    description: ${description}
    version: ${version}

# Override the default security properties, defined in org.springframework.boot.autoconfigure.security.SecurityProperties
security:
  user:
    name: operations
    password: operations
  basic:
    enabled: false
    realm: example

# app specific properties
example:
    serviceCode: ${name}
    serviceInstance: \${random.int[1,65536]}
    realm: development
    queueName: example-queue
    exchangeName: example-exchange
    deadLetterExchangeName: dead-letter-exchange
    deadLetterQueueName: dead-letter-queue
    messageRetryAttempts: 3
    foo: default


#---------- profile specific overrides ----------#

---
spring:
    profiles: bamboo
example:
    realm: bamboo
